import { PoAmendmentResponse } from "@/components/tool-response";
import { Badge } from "@/components/ui/badge";
import { CodeValue } from "@/components/ui/code-value";
import { AGENT_ALLOWED_TOOLS, type AgentStep } from "@/lib/domain/agent-steps";
import type { ReactNode } from "react";

function duration(step: AgentStep) {
  if (!step.startedAt || !step.completedAt) return null;
  const seconds =
    (Date.parse(step.completedAt) - Date.parse(step.startedAt)) / 1000;
  return `${seconds.toFixed(1)} s`;
}

/**
 * Agent work on a case as an ordered sequence. Price variance produces one
 * step today; the rendering does not assume there is only one.
 */
export function AgentStepsSequence({
  steps,
  renderStepBody,
}: {
  steps: readonly AgentStep[];
  /** What to show inside each step (tool calls, output, or both). */
  renderStepBody: (step: AgentStep) => ReactNode;
}) {
  if (steps.length === 0) {
    return (
      <p className="text-sm text-neutral-600 dark:text-neutral-400">
        No agent steps recorded yet.
      </p>
    );
  }
  return (
    <ol className="space-y-4">
      {steps.map((step, index) => (
        <li
          key={`${step.agentName}-${index}`}
          className="rounded-lg border border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-950"
        >
          <header className="flex flex-wrap items-baseline gap-x-3 gap-y-1 border-b border-neutral-200 px-4 py-3 dark:border-neutral-800">
            <span className="font-mono text-xs text-neutral-500">
              Step {index + 1} of {steps.length}
            </span>
            <h2 className="text-sm font-semibold">{step.agentName}</h2>
            {duration(step) && (
              <span className="text-xs text-neutral-500">{duration(step)}</span>
            )}
            <p className="w-full text-sm text-neutral-600 dark:text-neutral-400">
              {step.objective}
            </p>
          </header>
          <div className="space-y-4 p-4">{renderStepBody(step)}</div>
        </li>
      ))}
    </ol>
  );
}

export function ToolCalls({ step }: { step: AgentStep }) {
  const allowed = AGENT_ALLOWED_TOOLS[step.agentName] ?? [];
  return (
    <div className="space-y-3">
      <p className="flex flex-wrap items-center gap-2 text-xs text-neutral-600 dark:text-neutral-400">
        Tools granted to this agent by the workflow:
        {allowed.map((tool) => (
          <Badge key={tool}>{tool}</Badge>
        ))}
        <span>
          Nothing else, including payment or supplier bank-detail tools.
        </span>
      </p>
      {step.toolCalls === null ? (
        <p className="text-sm text-neutral-600 dark:text-neutral-400">
          The backend did not record tool calls for this step.
        </p>
      ) : step.toolCalls.length === 0 ? (
        <p className="text-sm text-neutral-600 dark:text-neutral-400">
          The agent made no tool calls.
        </p>
      ) : (
        step.toolCalls.map((call, index) => (
          <div
            key={index}
            className="space-y-3 rounded-md border border-neutral-200 p-3 dark:border-neutral-800"
          >
            <p className="flex flex-wrap items-center gap-2 text-sm">
              <span className="font-medium">{call.toolName}</span>
              <span className="text-neutral-500">input</span>
              <CodeValue>{`poNumber: ${call.input.poNumber}`}</CodeValue>
              <span className="text-xs text-neutral-500">
                passed from workflow state, not generated by the model
              </span>
            </p>
            <PoAmendmentResponse lookup={call.response} />
          </div>
        ))
      )}
    </div>
  );
}
