import { z } from "zod";
import type { ExceptionType } from "./matching";
import {
  agentDecisionSchema,
  poAmendmentLookupSchema,
  type AgentDecision,
} from "./resolution";

// An exception case records the agent work done on it as an ordered list of
// steps. Price variance produces one step today (the n8n "Price Variance
// Investigation Agent"). The list leaves room for agents that run before
// resolution (section 28) and for other exception types (section 32.2)
// without changing the case shape.

// --- Tool calls ---------------------------------------------------------------

export const toolCallSchema = z.discriminatedUnion("toolName", [
  z.object({
    toolName: z.literal("Get PO Amendment"),
    /** Passed from workflow state, not generated by the model (section 12.3). */
    input: z.object({ poNumber: z.string() }),
    response: poAmendmentLookupSchema,
  }),
]);

export type ToolCall = z.infer<typeof toolCallSchema>;

// --- Output schemas -----------------------------------------------------------

/**
 * Structured output schemas by id. Each agent step declares which one its
 * output follows. PRICE_VARIANCE_RESOLUTION is the n8n "Exception Resolution
 * Output Schema", unchanged.
 */
export const AGENT_OUTPUT_SCHEMAS = {
  PRICE_VARIANCE_RESOLUTION: agentDecisionSchema,
} as const;

export type AgentOutputSchemaId = keyof typeof AGENT_OUTPUT_SCHEMAS;

/** The resolution output schema for each exception type with an agent path. */
export const RESOLUTION_OUTPUT_SCHEMA_BY_EXCEPTION_TYPE: Partial<
  Record<ExceptionType, AgentOutputSchemaId>
> = {
  PRICE_VARIANCE: "PRICE_VARIANCE_RESOLUTION",
};

// --- Steps --------------------------------------------------------------------

const stepBase = {
  agentName: z.string().min(1),
  objective: z.string().min(1),
  /** Null when the backend does not record tool calls (n8n does not yet). */
  toolCalls: z.array(toolCallSchema).nullable(),
  startedAt: z.iso.datetime({ offset: true }).nullable(),
  completedAt: z.iso.datetime({ offset: true }).nullable(),
};

/** Discriminated on outputSchemaId; a new output schema adds a member. */
export const agentStepSchema = z.discriminatedUnion("outputSchemaId", [
  z.object({
    ...stepBase,
    outputSchemaId: z.literal("PRICE_VARIANCE_RESOLUTION"),
    output: agentDecisionSchema,
  }),
]);

export type AgentStep = z.infer<typeof agentStepSchema>;

export const PRICE_VARIANCE_AGENT = {
  agentName: "Price Variance Investigation Agent",
  objective:
    "Investigate the reason for a deterministic price variance and recommend a next action.",
} as const;

/**
 * The step whose output governance evaluates: the last one, which must
 * follow the resolution schema registered for the exception type.
 */
export function resolutionStep(
  steps: readonly AgentStep[],
  exceptionType: ExceptionType,
): AgentStep & { output: AgentDecision } {
  const last = steps.at(-1);
  const expected = RESOLUTION_OUTPUT_SCHEMA_BY_EXCEPTION_TYPE[exceptionType];
  if (!expected) {
    throw new Error(
      `No agent resolution schema is registered for ${exceptionType}.`,
    );
  }
  if (!last || last.outputSchemaId !== expected) {
    throw new Error(
      `The final agent step must produce ${expected} for ${exceptionType}; got ${last?.outputSchemaId ?? "no steps"}.`,
    );
  }
  return last;
}
